// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOxHdbJF3ZV4MXqCS_OlwdZfJWKqB9pM',
    appId: '1:19861251902:web:90b789bbde266da7bc6e6f',
    messagingSenderId: '19861251902',
    projectId: 'ecomm-98e7f',
    authDomain: 'ecomm-98e7f.firebaseapp.com',
    storageBucket: 'ecomm-98e7f.firebasestorage.app',
    measurementId: 'G-PGM4TPLENJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YTTxUuNNLnn6y_lnjSjsFc-rwzuwB4I',
    appId: '1:19861251902:android:faf6a8c0ff9ea415bc6e6f',
    messagingSenderId: '19861251902',
    projectId: 'ecomm-98e7f',
    storageBucket: 'ecomm-98e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7VdHKWkrMeOgMW_7wv9oQLp2oDk9X_4',
    appId: '1:19861251902:ios:891bb26598a906d1bc6e6f',
    messagingSenderId: '19861251902',
    projectId: 'ecomm-98e7f',
    storageBucket: 'ecomm-98e7f.firebasestorage.app',
    iosBundleId: 'com.1234.ecomflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7VdHKWkrMeOgMW_7wv9oQLp2oDk9X_4',
    appId: '1:19861251902:ios:891bb26598a906d1bc6e6f',
    messagingSenderId: '19861251902',
    projectId: 'ecomm-98e7f',
    storageBucket: 'ecomm-98e7f.firebasestorage.app',
    iosBundleId: 'com.1234.ecomflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASOxHdbJF3ZV4MXqCS_OlwdZfJWKqB9pM',
    appId: '1:19861251902:web:781e6f2a9a402a23bc6e6f',
    messagingSenderId: '19861251902',
    projectId: 'ecomm-98e7f',
    authDomain: 'ecomm-98e7f.firebaseapp.com',
    storageBucket: 'ecomm-98e7f.firebasestorage.app',
    measurementId: 'G-G5E5XM6GHH',
  );
}
